package ar.com.smg.aptoservicio;

import ar.com.smg.aptoservicio.Person;
import ar.com.smg.aptoservicio.Response;
global Response response;

rule "BIP_0" extends "ar.com.smg.aptoservicio.VIP"
	ruleflow-group "BIP-group"
    when
		
	then
end

rule "BIP_1" extends "ar.com.smg.aptoservicio.VIP"
    ruleflow-group "BIP-group"	
	when
		
	then
		
end

rule "BIP_2" extends "ar.com.smg.aptoservicio.VIP"
	ruleflow-group "BIP-group"
	when
		
	then
		
end