package ar.com.smg.aptoservicio;



rule "reglamanual_1"
	ruleflow-group "AptoServicio-group"
	when
		person(age >= 18, age <= 24, gender == "M", percentil >= 0, percentil <= 50)
	then
	   
		response.setType(true);
		response.setMessage("Esta OK");
		update(response);
		System.out.println("Entro por la regla ok");
end

rule "reglamanual_2"
	ruleflow-group "AptoServicio-group"
	when
		person(age >= 25, age <= 54, gender == "M", percentil >= 0, percentil <= 50)
	then

		response.setType(true);
		response.setMessage("Esta OK");
		update(response);
		System.out.println("Entro por la regla ok");
end

