package ar.com.smg.futurosocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Plan implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nombre;
   private java.lang.Boolean disponible;

   public Plan()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Boolean getDisponible()
   {
      return this.disponible;
   }

   public void setDisponible(java.lang.Boolean disponible)
   {
      this.disponible = disponible;
   }

   public Plan(java.lang.String nombre, java.lang.Boolean disponible)
   {
      this.nombre = nombre;
      this.disponible = disponible;
   }

}