package ar.com.smg.futurosocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean estado;
   private java.lang.String mensaje;

   public Respuesta()
   {
   }

   public java.lang.Boolean getEstado()
   {
      return this.estado;
   }

   public void setEstado(java.lang.Boolean estado)
   {
      this.estado = estado;
   }

   public java.lang.String getMensaje()
   {
      return this.mensaje;
   }

   public void setMensaje(java.lang.String mensaje)
   {
      this.mensaje = mensaje;
   }

   public Respuesta(java.lang.Boolean estado, java.lang.String mensaje)
   {
      this.estado = estado;
      this.mensaje = mensaje;
   }

}