package ar.com.smg.aptoservicio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private int age;
   private java.lang.String gender;
   private double percentil;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getAge()
   {
      return this.age;
   }

   public void setAge(int age)
   {
      this.age = age;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public double getPercentil()
   {
      return this.percentil;
   }

   public void setPercentil(double percentil)
   {
      this.percentil = percentil;
   }

   public Person(java.lang.String name, int age, java.lang.String gender,
         double percentil)
   {
      this.name = name;
      this.age = age;
      this.gender = gender;
      this.percentil = percentil;
   }

}