package ar.com.smg.aptoservicio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean type;
   private java.lang.String messaje;

   public Response()
   {
   }

   public java.lang.Boolean getType()
   {
      return this.type;
   }

   public void setType(java.lang.Boolean type)
   {
      this.type = type;
   }

   public java.lang.String getMessaje()
   {
      return this.messaje;
   }

   public void setMessaje(java.lang.String messaje)
   {
      this.messaje = messaje;
   }

   public Response(java.lang.Boolean type, java.lang.String messaje)
   {
      this.type = type;
      this.messaje = messaje;
   }

}