package ar.com.smg.aptoservicio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public static java.lang.Boolean type;
   public static java.lang.String message;

   public Response()
   {
   }

   public java.lang.Boolean getType()
   {
      return this.type;
   }

   public void setType(java.lang.Boolean type)
   {
      this.type = type;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public Response(java.lang.Boolean type, java.lang.String message)
   {
      this.type = type;
      this.message = message;
   }

}