package ar.com.smg.aptoservicio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Services implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Services() {
    }

}