package ar.com.smg.aptoservicio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Services implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String services;

   public Services()
   {
   }

   public java.lang.String getServices()
   {
      return this.services;
   }

   public void setServices(java.lang.String services)
   {
      this.services = services;
   }

   public Services(java.lang.String services)
   {
      this.services = services;
   }

}